name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        compiler: [ g++, clang++ ]
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
